version: '3'
services:
    web:
        build: ./app
        container_name: fm
        ports:
            - 3000:3000
        volumes:
            - ./app/web:/app
            - ./app/web/node_modules:/app/node_modules
        tty: true
        command: npm run dev